spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks
    webapp:
      application-path: /
    authorization:
      enabled: true


logging:
  level:
    ch.lt.home: DEBUG
